apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: name
  annotations:
    github.com/project-slug: Aluush/jdsjds

spec:
  type: service
  owner: user:guest
  lifecycle: experimental
